const ICONS: { [key: string]: string } = {};
export const ICON_NAMES: string[] = [];
ICONS["Addteam"] = 'addteam.png';
ICON_NAMES.push("Addteam");
ICONS["Adduser"] = 'adduser.png';
ICON_NAMES.push("Adduser");
ICONS["Alert Fill"] = 'alert-fill.png';
ICON_NAMES.push("Alert Fill");
ICONS["Alipay Circle Fill"] = 'alipay-circle-fill.png';
ICON_NAMES.push("Alipay Circle Fill");
ICONS["Aliwangwang Fill"] = 'aliwangwang-fill.png';
ICON_NAMES.push("Aliwangwang Fill");
ICONS["Android Fill"] = 'android-fill.png';
ICON_NAMES.push("Android Fill");
ICONS["Apartment"] = 'apartment.png';
ICON_NAMES.push("Apartment");
ICONS["Api Fill"] = 'api-fill.png';
ICON_NAMES.push("Api Fill");
ICONS["Apple Fill"] = 'apple-fill.png';
ICON_NAMES.push("Apple Fill");
ICONS["Appstore"] = 'appstore.png';
ICON_NAMES.push("Appstore");
ICONS["Appstoreadd"] = 'appstoreadd.png';
ICON_NAMES.push("Appstoreadd");
ICONS["Areachart"] = 'areachart.png';
ICON_NAMES.push("Areachart");
ICONS["Arrowdown"] = 'arrowdown.png';
ICON_NAMES.push("Arrowdown");
ICONS["Arrowleft"] = 'arrowleft.png';
ICON_NAMES.push("Arrowleft");
ICONS["Arrowright"] = 'arrowright.png';
ICON_NAMES.push("Arrowright");
ICONS["Arrowup"] = 'arrowup.png';
ICON_NAMES.push("Arrowup");
ICONS["Audio Fill"] = 'audio-fill.png';
ICON_NAMES.push("Audio Fill");
ICONS["Audio"] = 'audio.png';
ICON_NAMES.push("Audio");
ICONS["Audiostatic"] = 'audiostatic.png';
ICON_NAMES.push("Audiostatic");
ICONS["Audit"] = 'audit.png';
ICON_NAMES.push("Audit");
ICONS["Bank Fill"] = 'bank-fill.png';
ICON_NAMES.push("Bank Fill");
ICONS["Barchart"] = 'barchart.png';
ICON_NAMES.push("Barchart");
ICONS["Barcode"] = 'barcode.png';
ICON_NAMES.push("Barcode");
ICONS["Batchfolding Fill"] = 'batchfolding-fill.png';
ICON_NAMES.push("Batchfolding Fill");
ICONS["Batchfolding"] = 'Batchfolding.png';
ICON_NAMES.push("Batchfolding");
ICONS["Behance Circle Fill"] = 'behance-circle-fill.png';
ICON_NAMES.push("Behance Circle Fill");
ICONS["Book"] = 'book.png';
ICON_NAMES.push("Book");
ICONS["Border Bottom"] = 'border-bottom.png';
ICON_NAMES.push("Border Bottom");
ICONS["Border Horizontal"] = 'border-horizontal.png';
ICON_NAMES.push("Border Horizontal");
ICONS["Border Inner"] = 'border-inner.png';
ICON_NAMES.push("Border Inner");
ICONS["Border Left"] = 'border-left.png';
ICON_NAMES.push("Border Left");
ICONS["Border Outer"] = 'border-outer.png';
ICON_NAMES.push("Border Outer");
ICONS["Border Right"] = 'border-right.png';
ICON_NAMES.push("Border Right");
ICONS["Border Top"] = 'border-top.png';
ICON_NAMES.push("Border Top");
ICONS["Border Verticle"] = 'border-verticle.png';
ICON_NAMES.push("Border Verticle");
ICONS["Border"] = 'border.png';
ICON_NAMES.push("Border");
ICONS["Bug Fill"] = 'bug-fill.png';
ICON_NAMES.push("Bug Fill");
ICONS["Bug"] = 'bug.png';
ICON_NAMES.push("Bug");
ICONS["Calculator"] = 'calculator.png';
ICON_NAMES.push("Calculator");
ICONS["Camera Fill"] = 'camera-fill.png';
ICON_NAMES.push("Camera Fill");
ICONS["Camera"] = 'camera.png';
ICON_NAMES.push("Camera");
ICONS["Car Fill"] = 'car-fill.png';
ICON_NAMES.push("Car Fill");
ICONS["Car"] = 'car.png';
ICON_NAMES.push("Car");
ICONS["Check Circle Fill"] = 'check-circle-fill.png';
ICON_NAMES.push("Check Circle Fill");
ICONS["Check Circle"] = 'check-circle.png';
ICON_NAMES.push("Check Circle");
ICONS["Check Square"] = 'check-square.png';
ICON_NAMES.push("Check Square");
ICONS["Chrome Fill"] = 'chrome-fill.png';
ICON_NAMES.push("Chrome Fill");
ICONS["Ci Circle Fill"] = 'CI-circle-fill.png';
ICON_NAMES.push("Ci Circle Fill");
ICONS["Ci"] = 'CI.png';
ICON_NAMES.push("Ci");
ICONS["Close Circle Fill"] = 'close-circle-fill.png';
ICON_NAMES.push("Close Circle Fill");
ICONS["Close Circle"] = 'close-circle.png';
ICON_NAMES.push("Close Circle");
ICONS["Close Square"] = 'close-square.png';
ICON_NAMES.push("Close Square");
ICONS["Cloud Download"] = 'cloud-download.png';
ICON_NAMES.push("Cloud Download");
ICONS["Cloud Server"] = 'cloud-server.png';
ICON_NAMES.push("Cloud Server");
ICONS["Cloud Sync"] = 'cloud-sync.png';
ICON_NAMES.push("Cloud Sync");
ICONS["Cloud Upload"] = 'cloud-upload.png';
ICON_NAMES.push("Cloud Upload");
ICONS["Cloud"] = 'cloud.png';
ICON_NAMES.push("Cloud");
ICONS["Cluster"] = 'cluster.png';
ICON_NAMES.push("Cluster");
ICONS["Codelibrary"] = 'codelibrary.png';
ICON_NAMES.push("Codelibrary");
ICONS["Colum Height"] = 'colum-height.png';
ICON_NAMES.push("Colum Height");
ICONS["Comment"] = 'comment.png';
ICON_NAMES.push("Comment");
ICONS["Compass Fill"] = 'compass-fill.png';
ICON_NAMES.push("Compass Fill");
ICONS["Compass"] = 'compass.png';
ICON_NAMES.push("Compass");
ICONS["Container"] = 'container.png';
ICON_NAMES.push("Container");
ICONS["Control"] = 'control.png';
ICON_NAMES.push("Control");
ICONS["Copyright Circle Fil"] = 'copyright-circle-fil.png';
ICON_NAMES.push("Copyright Circle Fil");
ICONS["Copyright"] = 'copyright.png';
ICON_NAMES.push("Copyright");
ICONS["Crown Fill"] = 'crown-fill.png';
ICON_NAMES.push("Crown Fill");
ICONS["Dashboard"] = 'dashboard.png';
ICON_NAMES.push("Dashboard");
ICONS["Database"] = 'database.png';
ICON_NAMES.push("Database");
ICONS["Deleteteam"] = 'deleteteam.png';
ICON_NAMES.push("Deleteteam");
ICONS["Deleteuser"] = 'deleteuser.png';
ICON_NAMES.push("Deleteuser");
ICONS["Detail"] = 'detail.png';
ICON_NAMES.push("Detail");
ICONS["Diff Fill"] = 'diff-fill.png';
ICON_NAMES.push("Diff Fill");
ICONS["Diff"] = 'diff.png';
ICON_NAMES.push("Diff");
ICONS["Dingtalk"] = 'dingtalk.png';
ICON_NAMES.push("Dingtalk");
ICONS["Dollar Circle Fill"] = 'Dollar-circle-fill.png';
ICON_NAMES.push("Dollar Circle Fill");
ICONS["Dollar"] = 'Dollar.png';
ICON_NAMES.push("Dollar");
ICONS["Doubleleft"] = 'doubleleft.png';
ICON_NAMES.push("Doubleleft");
ICONS["Doubleright"] = 'doubleright.png';
ICON_NAMES.push("Doubleright");
ICONS["Down Circle Fill"] = 'down-circle-fill.png';
ICON_NAMES.push("Down Circle Fill");
ICONS["Down Circle"] = 'down-circle.png';
ICON_NAMES.push("Down Circle");
ICONS["Down Square"] = 'down-square.png';
ICON_NAMES.push("Down Square");
ICONS["Down"] = 'down.png';
ICON_NAMES.push("Down");
ICONS["Download"] = 'download.png';
ICON_NAMES.push("Download");
ICONS["Dropbox"] = 'dropbox.png';
ICON_NAMES.push("Dropbox");
ICONS["Earth"] = 'earth.png';
ICON_NAMES.push("Earth");
ICONS["Edit Fill"] = 'edit-fill.png';
ICON_NAMES.push("Edit Fill");
ICONS["Edit Square"] = 'edit-square.png';
ICON_NAMES.push("Edit Square");
ICONS["Error Fill"] = 'error-fill.png';
ICON_NAMES.push("Error Fill");
ICONS["Euro Circle Fill"] = 'EURO-circle-fill.png';
ICON_NAMES.push("Euro Circle Fill");
ICONS["Euro"] = 'EURO.png';
ICON_NAMES.push("Euro");
ICONS["Export"] = 'export.png';
ICON_NAMES.push("Export");
ICONS["Eye"] = 'eye.png';
ICON_NAMES.push("Eye");
ICONS["Fall"] = 'fall.png';
ICON_NAMES.push("Fall");
ICONS["File Add Fill"] = 'file-add-fill.png';
ICON_NAMES.push("File Add Fill");
ICONS["File Add"] = 'file-add.png';
ICON_NAMES.push("File Add");
ICONS["File Copy Fill"] = 'file-copy-fill.png';
ICON_NAMES.push("File Copy Fill");
ICONS["File Copy"] = 'file-copy.png';
ICON_NAMES.push("File Copy");
ICONS["File Excel Fill"] = 'file-excel-fill.png';
ICON_NAMES.push("File Excel Fill");
ICONS["File Excel"] = 'file-excel.png';
ICON_NAMES.push("File Excel");
ICONS["File Exception"] = 'file-exception.png';
ICON_NAMES.push("File Exception");
ICONS["File Exclamation Fil"] = 'file-exclamation-fil.png';
ICON_NAMES.push("File Exclamation Fil");
ICONS["File Exclamation"] = 'file-exclamation.png';
ICON_NAMES.push("File Exclamation");
ICONS["File Fill"] = 'file-fill.png';
ICON_NAMES.push("File Fill");
ICONS["File Image Fill"] = 'file-image-fill.png';
ICON_NAMES.push("File Image Fill");
ICONS["File Image"] = 'file-image.png';
ICON_NAMES.push("File Image");
ICONS["File Markdown Fill"] = 'file-markdown-fill.png';
ICON_NAMES.push("File Markdown Fill");
ICONS["File Markdown"] = 'file-markdown.png';
ICON_NAMES.push("File Markdown");
ICONS["File Pdf Fill"] = 'file-pdf-fill.png';
ICON_NAMES.push("File Pdf Fill");
ICONS["File Pdf"] = 'file-pdf.png';
ICON_NAMES.push("File Pdf");
ICONS["File Ppt Fill"] = 'file-ppt-fill.png';
ICON_NAMES.push("File Ppt Fill");
ICONS["File Ppt"] = 'file-ppt.png';
ICON_NAMES.push("File Ppt");
ICONS["File Text Fill"] = 'file-text-fill.png';
ICON_NAMES.push("File Text Fill");
ICONS["File Text"] = 'file-text.png';
ICON_NAMES.push("File Text");
ICONS["File Unknown Fill"] = 'file-unknown-fill.png';
ICON_NAMES.push("File Unknown Fill");
ICONS["File Unknown"] = 'file-unknown.png';
ICON_NAMES.push("File Unknown");
ICONS["File Word Fill"] = 'file-word-fill.png';
ICON_NAMES.push("File Word Fill");
ICONS["File Word"] = 'file-word.png';
ICON_NAMES.push("File Word");
ICONS["File Zip Fill"] = 'file-zip-fill.png';
ICON_NAMES.push("File Zip Fill");
ICONS["File Zip"] = 'file-zip.png';
ICON_NAMES.push("File Zip");
ICONS["File"] = 'file.png';
ICON_NAMES.push("File");
ICONS["Filedone"] = 'filedone.png';
ICON_NAMES.push("Filedone");
ICONS["Fileprotect"] = 'fileprotect.png';
ICON_NAMES.push("Fileprotect");
ICONS["Filesearch"] = 'filesearch.png';
ICON_NAMES.push("Filesearch");
ICONS["Filesync"] = 'filesync.png';
ICON_NAMES.push("Filesync");
ICONS["Fire"] = 'fire.png';
ICON_NAMES.push("Fire");
ICONS["Folder"] = 'folder.png';
ICON_NAMES.push("Folder");
ICONS["Frown Fill"] = 'frown-fill.png';
ICON_NAMES.push("Frown Fill");
ICONS["Frown"] = 'frown.png';
ICON_NAMES.push("Frown");
ICONS["Fullscreen Exit"] = 'fullscreen-exit.png';
ICON_NAMES.push("Fullscreen Exit");
ICONS["Fullscreen"] = 'fullscreen.png';
ICON_NAMES.push("Fullscreen");
ICONS["Fund"] = 'fund.png';
ICON_NAMES.push("Fund");
ICONS["Gateway"] = 'gateway.png';
ICON_NAMES.push("Gateway");
ICONS["Gift"] = 'gift.png';
ICON_NAMES.push("Gift");
ICONS["Gitlab Fill"] = 'Gitlab-fill.png';
ICON_NAMES.push("Gitlab Fill");
ICONS["Highlight Fill"] = 'highlight-fill.png';
ICON_NAMES.push("Highlight Fill");
ICONS["Html Fill"] = 'HTML-fill.png';
ICON_NAMES.push("Html Fill");
ICONS["Import"] = 'Import.png';
ICON_NAMES.push("Import");
ICONS["Info Circle Fill"] = 'info-circle-fill.png';
ICON_NAMES.push("Info Circle Fill");
ICONS["Info Circle"] = 'info-circle.png';
ICON_NAMES.push("Info Circle");
ICONS["Insurance Fill"] = 'insurance-fill.png';
ICON_NAMES.push("Insurance Fill");
ICONS["Interation"] = 'interation.png';
ICON_NAMES.push("Interation");
ICONS["Issuesclose"] = 'issuesclose.png';
ICON_NAMES.push("Issuesclose");
ICONS["Laptop"] = 'laptop.png';
ICON_NAMES.push("Laptop");
ICONS["Layout"] = 'layout.png';
ICON_NAMES.push("Layout");
ICONS["Left Circle Fill"] = 'left-circle-fill.png';
ICON_NAMES.push("Left Circle Fill");
ICONS["Left Circle"] = 'left-circle.png';
ICON_NAMES.push("Left Circle");
ICONS["Left Square"] = 'left-square.png';
ICON_NAMES.push("Left Square");
ICONS["Linechart"] = 'linechart.png';
ICON_NAMES.push("Linechart");
ICONS["Link"] = 'link.png';
ICON_NAMES.push("Link");
ICONS["Location"] = 'location.png';
ICON_NAMES.push("Location");
ICONS["Logout"] = 'logout.png';
ICON_NAMES.push("Logout");
ICONS["Mail Fill"] = 'mail-fill.png';
ICON_NAMES.push("Mail Fill");
ICONS["Meh"] = 'meh.png';
ICON_NAMES.push("Meh");
ICONS["Message"] = 'message.png';
ICON_NAMES.push("Message");
ICONS["Minus Circle Fill"] = 'minus-circle-fill.png';
ICON_NAMES.push("Minus Circle Fill");
ICONS["Minus Circle"] = 'minus-circle.png';
ICON_NAMES.push("Minus Circle");
ICONS["Minus Square"] = 'minus-square.png';
ICON_NAMES.push("Minus Square");
ICONS["Mobile"] = 'mobile.png';
ICON_NAMES.push("Mobile");
ICONS["Notification"] = 'notification.png';
ICON_NAMES.push("Notification");
ICONS["Phone Fill"] = 'phone-fill.png';
ICON_NAMES.push("Phone Fill");
ICONS["Piechart"] = 'piechart.png';
ICON_NAMES.push("Piechart");
ICONS["Play Circle"] = 'play-circle.png';
ICON_NAMES.push("Play Circle");
ICONS["Play Square"] = 'play-square.png';
ICON_NAMES.push("Play Square");
ICONS["Plus Circle Fill"] = 'plus-circle-fill.png';
ICON_NAMES.push("Plus Circle Fill");
ICONS["Plus Circle"] = 'plus-circle.png';
ICON_NAMES.push("Plus Circle");
ICONS["Plus Square"] = 'plus-square.png';
ICON_NAMES.push("Plus Square");
ICONS["Pointmap"] = 'pointmap.png';
ICON_NAMES.push("Pointmap");
ICONS["Pound"] = 'Pound.png';
ICON_NAMES.push("Pound");
ICONS["Poweroff"] = 'poweroff.png';
ICON_NAMES.push("Poweroff");
ICONS["Printer"] = 'printer.png';
ICON_NAMES.push("Printer");
ICONS["Project"] = 'project.png';
ICON_NAMES.push("Project");
ICONS["Propertysafety Fill"] = 'propertysafety-fill.png';
ICON_NAMES.push("Propertysafety Fill");
ICONS["Propertysafety"] = 'propertysafety.png';
ICON_NAMES.push("Propertysafety");
ICONS["Pushpin Fill"] = 'pushpin-fill.png';
ICON_NAMES.push("Pushpin Fill");
ICONS["Qq"] = 'QQ.png';
ICON_NAMES.push("Qq");
ICONS["Qrcode"] = 'qrcode.png';
ICON_NAMES.push("Qrcode");
ICONS["Question Circle Fill"] = 'question-circle-fill.png';
ICON_NAMES.push("Question Circle Fill");
ICONS["Question Circle"] = 'question-circle.png';
ICON_NAMES.push("Question Circle");
ICONS["Radarchart"] = 'radarchart.png';
ICON_NAMES.push("Radarchart");
ICONS["Radius Bottomleft"] = 'radius-bottomleft.png';
ICON_NAMES.push("Radius Bottomleft");
ICONS["Radius Bottomright"] = 'radius-bottomright.png';
ICON_NAMES.push("Radius Bottomright");
ICONS["Radius Setting"] = 'radius-setting.png';
ICON_NAMES.push("Radius Setting");
ICONS["Radius Upleft"] = 'radius-upleft.png';
ICON_NAMES.push("Radius Upleft");
ICONS["Radius Upright"] = 'radius-upright.png';
ICON_NAMES.push("Radius Upright");
ICONS["Read"] = 'read.png';
ICON_NAMES.push("Read");
ICONS["Reconciliation"] = 'reconciliation.png';
ICON_NAMES.push("Reconciliation");
ICONS["Redenvelope"] = 'redenvelope.png';
ICON_NAMES.push("Redenvelope");
ICONS["Redo"] = 'redo.png';
ICON_NAMES.push("Redo");
ICONS["Reload"] = 'reload.png';
ICON_NAMES.push("Reload");
ICONS["Reloadtime"] = 'reloadtime.png';
ICON_NAMES.push("Reloadtime");
ICONS["Right Circle Fill"] = 'right-circle-fill.png';
ICON_NAMES.push("Right Circle Fill");
ICONS["Right Circle"] = 'right-circle.png';
ICON_NAMES.push("Right Circle");
ICONS["Right Square"] = 'right-square.png';
ICON_NAMES.push("Right Square");
ICONS["Robot Fill"] = 'robot-fill.png';
ICON_NAMES.push("Robot Fill");
ICONS["Robot"] = 'robot.png';
ICON_NAMES.push("Robot");
ICONS["Rocket Fill"] = 'rocket-fill.png';
ICON_NAMES.push("Rocket Fill");
ICONS["Safetycertificate F"] = 'safetycertificate-f.png';
ICON_NAMES.push("Safetycertificate F");
ICONS["Save"] = 'save.png';
ICON_NAMES.push("Save");
ICONS["Securityscan Fill"] = 'securityscan-fill.png';
ICON_NAMES.push("Securityscan Fill");
ICONS["Securityscan"] = 'securityscan.png';
ICON_NAMES.push("Securityscan");
ICONS["Setting"] = 'setting.png';
ICON_NAMES.push("Setting");
ICONS["Sever"] = 'sever.png';
ICON_NAMES.push("Sever");
ICONS["Shortcut Fill"] = 'shortcut-fill.png';
ICON_NAMES.push("Shortcut Fill");
ICONS["Signal Fill"] = 'signal-fill.png';
ICON_NAMES.push("Signal Fill");
ICONS["Skype Fill"] = 'skype-fill.png';
ICON_NAMES.push("Skype Fill");
ICONS["Sliders"] = 'sliders.png';
ICON_NAMES.push("Sliders");
ICONS["Smile"] = 'smile.png';
ICON_NAMES.push("Smile");
ICONS["Snippets Fill"] = 'snippets-fill.png';
ICON_NAMES.push("Snippets Fill");
ICONS["Snippets"] = 'snippets.png';
ICON_NAMES.push("Snippets");
ICONS["Solution"] = 'solution.png';
ICON_NAMES.push("Solution");
ICONS["Sort Ascending"] = 'sort-ascending.png';
ICON_NAMES.push("Sort Ascending");
ICONS["Sort Descending"] = 'sort-descending.png';
ICON_NAMES.push("Sort Descending");
ICONS["Sound"] = 'sound.png';
ICON_NAMES.push("Sound");
ICONS["Star Fill"] = 'star-fill.png';
ICON_NAMES.push("Star Fill");
ICONS["Stop"] = 'stop.png';
ICON_NAMES.push("Stop");
ICONS["Swap"] = 'swap.png';
ICON_NAMES.push("Swap");
ICONS["Switchuser"] = 'switchuser.png';
ICON_NAMES.push("Switchuser");
ICONS["Sync"] = 'sync.png';
ICON_NAMES.push("Sync");
ICONS["Tablet"] = 'tablet.png';
ICON_NAMES.push("Tablet");
ICONS["Tag Fill"] = 'tag-fill.png';
ICON_NAMES.push("Tag Fill");
ICONS["Tags Fill"] = 'tags-fill.png';
ICON_NAMES.push("Tags Fill");
ICONS["Team"] = 'team.png';
ICON_NAMES.push("Team");
ICONS["Thunderbolt Fill"] = 'thunderbolt-fill.png';
ICON_NAMES.push("Thunderbolt Fill");
ICONS["Thunderbolt"] = 'thunderbolt.png';
ICON_NAMES.push("Thunderbolt");
ICONS["Time Circle"] = 'time-circle.png';
ICON_NAMES.push("Time Circle");
ICONS["Timeout"] = 'timeout.png';
ICON_NAMES.push("Timeout");
ICONS["Totop"] = 'totop.png';
ICON_NAMES.push("Totop");
ICONS["Trademark"] = 'trademark.png';
ICON_NAMES.push("Trademark");
ICONS["Transaction"] = 'transaction.png';
ICON_NAMES.push("Transaction");
ICONS["Twitter"] = 'twitter.png';
ICON_NAMES.push("Twitter");
ICONS["Undo"] = 'undo.png';
ICON_NAMES.push("Undo");
ICONS["Unlike Fill"] = 'unlike-fill.png';
ICON_NAMES.push("Unlike Fill");
ICONS["Unlock Fill"] = 'unlock-fill.png';
ICON_NAMES.push("Unlock Fill");
ICONS["Up Circle Fill"] = 'up-circle-fill.png';
ICON_NAMES.push("Up Circle Fill");
ICONS["Up Circle"] = 'up-circle.png';
ICON_NAMES.push("Up Circle");
ICONS["Up Square"] = 'up-square.png';
ICON_NAMES.push("Up Square");
ICONS["Upload"] = 'upload.png';
ICON_NAMES.push("Upload");
ICONS["User"] = 'user.png';
ICON_NAMES.push("User");
ICONS["Verified"] = 'verified.png';
ICON_NAMES.push("Verified");
ICONS["Vertical Align Botto"] = 'vertical-align-botto.png';
ICON_NAMES.push("Vertical Align Botto");
ICONS["Vertical Align Middl"] = 'vertical-align-middl.png';
ICON_NAMES.push("Vertical Align Middl");
ICONS["Vertical Align Top"] = 'vertical-align-top.png';
ICON_NAMES.push("Vertical Align Top");
ICONS["Video"] = 'video.png';
ICON_NAMES.push("Video");
ICONS["Videocameraadd"] = 'videocameraadd.png';
ICON_NAMES.push("Videocameraadd");
ICONS["Wallet"] = 'wallet.png';
ICON_NAMES.push("Wallet");
ICONS["Warning Circle"] = 'warning-circle.png';
ICON_NAMES.push("Warning Circle");
ICONS["Wechat Fill"] = 'wechat-fill.png';
ICON_NAMES.push("Wechat Fill");
ICONS["Weibo Square Fill"] = 'weibo-square-fill.png';
ICON_NAMES.push("Weibo Square Fill");
ICONS["Weibo"] = 'weibo.png';
ICON_NAMES.push("Weibo");
ICONS["Whatsapp"] = 'whatsapp.png';
ICON_NAMES.push("Whatsapp");
ICONS["Windows Fill"] = 'windows-fill.png';
ICON_NAMES.push("Windows Fill");
ICONS["Wrench Fill"] = 'wrench-fill.png';
ICON_NAMES.push("Wrench Fill");
ICONS["Yahoo Fill"] = 'yahoo-fill.png';
ICON_NAMES.push("Yahoo Fill");
ICONS["Youtube Fill"] = 'Youtube-fill.png';
ICON_NAMES.push("Youtube Fill");
ICONS["Youtube"] = 'Youtube.png';
ICON_NAMES.push("Youtube");
ICONS["Yuan"] = 'YUAN.png';
ICON_NAMES.push("Yuan");
ICONS["Yuque Fill"] = 'yuque-fill.png';
ICON_NAMES.push("Yuque Fill");
ICONS["Zhihu Square Fill"] = 'zhihu-square-fill.png';
ICON_NAMES.push("Zhihu Square Fill");
ICONS["Zoomin"] = 'zoomin.png';
ICON_NAMES.push("Zoomin");
ICONS["Zoomout"] = 'zoomout.png';
ICON_NAMES.push("Zoomout");
export default ICONS;